// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package testdata

import defaults "github.com/creasty/defaults"

type BasicConfigOption func(b *BasicConfig)

// NewBasicConfigWithOptions creates a new BasicConfig with the passed in options set
func NewBasicConfigWithOptions(opts ...BasicConfigOption) *BasicConfig {
	b := &BasicConfig{}
	for _, o := range opts {
		o(b)
	}
	return b
}

// NewBasicConfigWithOptionsAndDefaults creates a new BasicConfig with the passed in options set starting from the defaults
func NewBasicConfigWithOptionsAndDefaults(opts ...BasicConfigOption) *BasicConfig {
	b := &BasicConfig{}
	defaults.MustSet(b)
	for _, o := range opts {
		o(b)
	}
	return b
}

// ToOption returns a new BasicConfigOption that sets the values from the passed in BasicConfig
func (b *BasicConfig) ToOption() BasicConfigOption {
	return func(to *BasicConfig) {
		to.Name = b.Name
		to.Port = b.Port
		to.Enabled = b.Enabled
		to.Timeout = b.Timeout
	}
}

// DebugMap returns a map form of BasicConfig for debugging
func (b *BasicConfig) DebugMap() map[string]any {
	debugMap := map[string]any{}
	if b.Name == "" {
		debugMap["Name"] = "(empty)"
	} else {
		debugMap["Name"] = b.Name
	}
	debugMap["Port"] = b.Port
	debugMap["Enabled"] = b.Enabled
	if b.Timeout == nil {
		debugMap["Timeout"] = "nil"
	} else {
		debugMap["Timeout"] = *b.Timeout
	}
	return debugMap
}

// FlatDebugMap returns a flattened map form of BasicConfig for debugging
// Nested maps are flattened using dot notation (e.g., "parent.child.field")
func (b *BasicConfig) FlatDebugMap() map[string]any {
	return flattenDebugMap(b.DebugMap())
}

// BasicConfigWithOptions configures an existing BasicConfig with the passed in options set
func BasicConfigWithOptions(b *BasicConfig, opts ...BasicConfigOption) *BasicConfig {
	for _, o := range opts {
		o(b)
	}
	return b
}

// WithOptions configures the receiver BasicConfig with the passed in options set
func (b *BasicConfig) WithOptions(opts ...BasicConfigOption) *BasicConfig {
	for _, o := range opts {
		o(b)
	}
	return b
}

// WithName returns an option that can set Name on a BasicConfig
func WithName(name string) BasicConfigOption {
	return func(b *BasicConfig) {
		b.Name = name
	}
}

// WithPort returns an option that can set Port on a BasicConfig
func WithPort(port int) BasicConfigOption {
	return func(b *BasicConfig) {
		b.Port = port
	}
}

// WithEnabled returns an option that can set Enabled on a BasicConfig
func WithEnabled(enabled bool) BasicConfigOption {
	return func(b *BasicConfig) {
		b.Enabled = enabled
	}
}

// WithTimeout returns an option that can set Timeout on a BasicConfig
func WithTimeout(timeout *int) BasicConfigOption {
	return func(b *BasicConfig) {
		b.Timeout = timeout
	}
}

// flattenDebugMap recursively flattens nested maps using dot notation
func flattenDebugMap(debugMap map[string]any) map[string]any {
	flattened := make(map[string]any, len(debugMap))
	for key, value := range debugMap {
		childMap, ok := value.(map[string]any)
		if ok {
			for fk, fv := range flattenDebugMap(childMap) {
				flattened[key+"."+fk] = fv
			}
			continue
		}
		flattened[key] = value
	}
	return flattened
}
