// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package testdata

import defaults "github.com/creasty/defaults"

type OptgenTagTestOption func(o *OptgenTagTest)

// NewOptgenTagTestWithOptions creates a new OptgenTagTest with the passed in options set
func NewOptgenTagTestWithOptions(opts ...OptgenTagTestOption) *OptgenTagTest {
	o := &OptgenTagTest{}
	for _, o := range opts {
		o(o)
	}
	return o
}

// NewOptgenTagTestWithOptionsAndDefaults creates a new OptgenTagTest with the passed in options set starting from the defaults
func NewOptgenTagTestWithOptionsAndDefaults(opts ...OptgenTagTestOption) *OptgenTagTest {
	o := &OptgenTagTest{}
	defaults.MustSet(o)
	for _, o := range opts {
		o(o)
	}
	return o
}

// ToOption returns a new OptgenTagTestOption that sets the values from the passed in OptgenTagTest
func (o *OptgenTagTest) ToOption() OptgenTagTestOption {
	return func(to *OptgenTagTest) {
		to.Name = o.Name
		to.ID = o.ID
		to.Port = o.Port
	}
}

// DebugMap returns a map form of OptgenTagTest for debugging
func (o *OptgenTagTest) DebugMap() map[string]any {
	debugMap := map[string]any{}
	if o.Name == "" {
		debugMap["Name"] = "(empty)"
	} else {
		debugMap["Name"] = o.Name
	}
	if o.ID == "" {
		debugMap["ID"] = "(empty)"
	} else {
		debugMap["ID"] = o.ID
	}
	debugMap["Port"] = o.Port
	return debugMap
}

// FlatDebugMap returns a flattened map form of OptgenTagTest for debugging
// Nested maps are flattened using dot notation (e.g., "parent.child.field")
func (o *OptgenTagTest) FlatDebugMap() map[string]any {
	var flatten func(m map[string]any) map[string]any
	flatten = func(m map[string]any) map[string]any {
		result := make(map[string]any, len(m))
		for key, value := range m {
			childMap, ok := value.(map[string]any)
			if ok {
				for childKey, childValue := range flatten(childMap) {
					result[key+"."+childKey] = childValue
				}
				continue
			}
			result[key] = value
		}
		return result
	}
	return flatten(o.DebugMap())
}

// OptgenTagTestWithOptions configures an existing OptgenTagTest with the passed in options set
func OptgenTagTestWithOptions(o *OptgenTagTest, opts ...OptgenTagTestOption) *OptgenTagTest {
	for _, o := range opts {
		o(o)
	}
	return o
}

// WithOptions configures the receiver OptgenTagTest with the passed in options set
func (o *OptgenTagTest) WithOptions(opts ...OptgenTagTestOption) *OptgenTagTest {
	for _, o := range opts {
		o(o)
	}
	return o
}

// WithName returns an option that can set Name on a OptgenTagTest
func WithName(name string) OptgenTagTestOption {
	return func(o *OptgenTagTest) {
		o.Name = name
	}
}

// WithPort returns an option that can set Port on a OptgenTagTest
func WithPort(port int) OptgenTagTestOption {
	return func(o *OptgenTagTest) {
		o.Port = port
	}
}
