// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package example

import (
	defaults "github.com/creasty/defaults"
	helpers "github.com/ecordell/optgen/helpers"
)

type ConfigOption func(c *Config)

// NewConfigWithOptions creates a new Config with the passed in options set
func NewConfigWithOptions(opts ...ConfigOption) *Config {
	c := &Config{}
	for _, o := range opts {
		o(c)
	}
	return c
}

// NewConfigWithOptionsAndDefaults creates a new Config with the passed in options set starting from the defaults
func NewConfigWithOptionsAndDefaults(opts ...ConfigOption) *Config {
	c := &Config{}
	defaults.MustSet(c)
	for _, o := range opts {
		o(c)
	}
	return c
}

// ToOption returns a new ConfigOption that sets the values from the passed in Config
func (c *Config) ToOption() ConfigOption {
	return func(to *Config) {
		to.Name = c.Name
		to.Port = c.Port
		to.Enabled = c.Enabled
		to.Timeout = c.Timeout
		to.Tags = c.Tags
		to.Metadata = c.Metadata
		to.Debug = c.Debug
	}
}

// DebugMap returns a map form of Config for debugging
func (c *Config) DebugMap() map[string]any {
	debugMap := map[string]any{}
	debugMap["Name"] = helpers.DebugValue(c.Name, false)
	debugMap["Port"] = helpers.DebugValue(c.Port, false)
	debugMap["Enabled"] = helpers.DebugValue(c.Enabled, false)
	debugMap["Timeout"] = helpers.DebugValue(c.Timeout, false)
	debugMap["Tags"] = helpers.DebugValue(c.Tags, true)
	debugMap["Metadata"] = helpers.DebugValue(c.Metadata, true)
	debugMap["Debug"] = helpers.DebugValue(c.Debug, false)
	return debugMap
}

// ConfigWithOptions configures an existing Config with the passed in options set
func ConfigWithOptions(c *Config, opts ...ConfigOption) *Config {
	for _, o := range opts {
		o(c)
	}
	return c
}

// WithOptions configures the receiver Config with the passed in options set
func (c *Config) WithOptions(opts ...ConfigOption) *Config {
	for _, o := range opts {
		o(c)
	}
	return c
}

// WithName returns an option that can set Name on a Config
func WithName(name string) ConfigOption {
	return func(c *Config) {
		c.Name = name
	}
}

// WithPort returns an option that can set Port on a Config
func WithPort(port int) ConfigOption {
	return func(c *Config) {
		c.Port = port
	}
}

// WithEnabled returns an option that can set Enabled on a Config
func WithEnabled(enabled bool) ConfigOption {
	return func(c *Config) {
		c.Enabled = enabled
	}
}

// WithTimeout returns an option that can set Timeout on a Config
func WithTimeout(timeout *int) ConfigOption {
	return func(c *Config) {
		c.Timeout = timeout
	}
}

// WithTags returns an option that can append Tagss to Config.Tags
func WithTags(tags string) ConfigOption {
	return func(c *Config) {
		c.Tags = append(c.Tags, tags)
	}
}

// SetTags returns an option that can set Tags on a Config
func SetTags(tags []string) ConfigOption {
	return func(c *Config) {
		c.Tags = tags
	}
}

// WithMetadata returns an option that can append Metadatas to Config.Metadata
func WithMetadata(key string, value interface{}) ConfigOption {
	return func(c *Config) {
		c.Metadata[key] = value
	}
}

// SetMetadata returns an option that can set Metadata on a Config
func SetMetadata(metadata map[string]interface{}) ConfigOption {
	return func(c *Config) {
		c.Metadata = metadata
	}
}

// WithDebug returns an option that can set Debug on a Config
func WithDebug(debug bool) ConfigOption {
	return func(c *Config) {
		c.Debug = debug
	}
}

type ServerOption func(s *Server)

// NewServerWithOptions creates a new Server with the passed in options set
func NewServerWithOptions(opts ...ServerOption) *Server {
	s := &Server{}
	for _, o := range opts {
		o(s)
	}
	return s
}

// NewServerWithOptionsAndDefaults creates a new Server with the passed in options set starting from the defaults
func NewServerWithOptionsAndDefaults(opts ...ServerOption) *Server {
	s := &Server{}
	defaults.MustSet(s)
	for _, o := range opts {
		o(s)
	}
	return s
}

// ToOption returns a new ServerOption that sets the values from the passed in Server
func (s *Server) ToOption() ServerOption {
	return func(to *Server) {
		to.Host = s.Host
		to.Port = s.Port
		to.TLS = s.TLS
		to.Cert = s.Cert
		to.Key = s.Key
		to.Workers = s.Workers
	}
}

// DebugMap returns a map form of Server for debugging
func (s *Server) DebugMap() map[string]any {
	debugMap := map[string]any{}
	debugMap["Host"] = helpers.DebugValue(s.Host, false)
	debugMap["Port"] = helpers.DebugValue(s.Port, false)
	debugMap["TLS"] = helpers.DebugValue(s.TLS, false)
	debugMap["Cert"] = helpers.SensitiveDebugValue(s.Cert)
	debugMap["Key"] = helpers.SensitiveDebugValue(s.Key)
	debugMap["Workers"] = helpers.DebugValue(s.Workers, false)
	return debugMap
}

// ServerWithOptions configures an existing Server with the passed in options set
func ServerWithOptions(s *Server, opts ...ServerOption) *Server {
	for _, o := range opts {
		o(s)
	}
	return s
}

// WithOptions configures the receiver Server with the passed in options set
func (s *Server) WithOptions(opts ...ServerOption) *Server {
	for _, o := range opts {
		o(s)
	}
	return s
}

// WithHost returns an option that can set Host on a Server
func WithHost(host string) ServerOption {
	return func(s *Server) {
		s.Host = host
	}
}

// WithPort returns an option that can set Port on a Server
func WithPort(port int) ServerOption {
	return func(s *Server) {
		s.Port = port
	}
}

// WithTLS returns an option that can set TLS on a Server
func WithTLS(tLS bool) ServerOption {
	return func(s *Server) {
		s.TLS = tLS
	}
}

// WithCert returns an option that can set Cert on a Server
func WithCert(cert string) ServerOption {
	return func(s *Server) {
		s.Cert = cert
	}
}

// WithKey returns an option that can set Key on a Server
func WithKey(key string) ServerOption {
	return func(s *Server) {
		s.Key = key
	}
}

// WithWorkers returns an option that can set Workers on a Server
func WithWorkers(workers int) ServerOption {
	return func(s *Server) {
		s.Workers = workers
	}
}
