// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package example

import (
	"fmt"
	defaults "github.com/creasty/defaults"
)

type ConfigOption func(c *Config)

// NewConfigWithOptions creates a new Config with the passed in options set
func NewConfigWithOptions(opts ...ConfigOption) *Config {
	c := &Config{}
	for _, o := range opts {
		o(c)
	}
	return c
}

// NewConfigWithOptionsAndDefaults creates a new Config with the passed in options set starting from the defaults
func NewConfigWithOptionsAndDefaults(opts ...ConfigOption) *Config {
	c := &Config{}
	defaults.MustSet(c)
	for _, o := range opts {
		o(c)
	}
	return c
}

// ToOption returns a new ConfigOption that sets the values from the passed in Config
func (c *Config) ToOption() ConfigOption {
	return func(to *Config) {
		to.Name = c.Name
		to.Port = c.Port
		to.Enabled = c.Enabled
		to.Timeout = c.Timeout
		to.Tags = c.Tags
		to.Metadata = c.Metadata
		to.Debug = c.Debug
	}
}

// DebugMap returns a map form of Config for debugging
func (c *Config) DebugMap() map[string]any {
	debugMap := map[string]any{}
	if c.Name == "" {
		debugMap["Name"] = "(empty)"
	} else {
		debugMap["Name"] = c.Name
	}
	debugMap["Port"] = c.Port
	debugMap["Enabled"] = c.Enabled
	if c.Timeout == nil {
		debugMap["Timeout"] = "nil"
	} else {
		debugMap["Timeout"] = *c.Timeout
	}
	if c.Tags == nil {
		debugMap["Tags"] = "nil"
	} else {
		debugTags := make([]any, 0, len(c.Tags))
		for _, v := range c.Tags {
			if v == "" {
				debugTags = append(debugTags, "(empty)")
			} else {
				debugTags = append(debugTags, v)
			}
		}
		debugMap["Tags"] = debugTags
	}
	if c.Metadata == nil {
		debugMap["Metadata"] = "nil"
	} else {
		debugMap["Metadata"] = fmt.Sprintf("%v", c.Metadata)
	}
	debugMap["Debug"] = c.Debug
	return debugMap
}

// ConfigWithOptions configures an existing Config with the passed in options set
func ConfigWithOptions(c *Config, opts ...ConfigOption) *Config {
	for _, o := range opts {
		o(c)
	}
	return c
}

// WithOptions configures the receiver Config with the passed in options set
func (c *Config) WithOptions(opts ...ConfigOption) *Config {
	for _, o := range opts {
		o(c)
	}
	return c
}

// WithConfigName returns an option that can set Name on a Config
func WithConfigName(name string) ConfigOption {
	return func(c *Config) {
		c.Name = name
	}
}

// WithConfigPort returns an option that can set Port on a Config
func WithConfigPort(port int) ConfigOption {
	return func(c *Config) {
		c.Port = port
	}
}

// WithConfigEnabled returns an option that can set Enabled on a Config
func WithConfigEnabled(enabled bool) ConfigOption {
	return func(c *Config) {
		c.Enabled = enabled
	}
}

// WithConfigTimeout returns an option that can set Timeout on a Config
func WithConfigTimeout(timeout *int) ConfigOption {
	return func(c *Config) {
		c.Timeout = timeout
	}
}

// WithConfigTags returns an option that can append Tagss to Config.Tags
func WithConfigTags(tags string) ConfigOption {
	return func(c *Config) {
		c.Tags = append(c.Tags, tags)
	}
}

// SetConfigTags returns an option that can set Tags on a Config
func SetConfigTags(tags []string) ConfigOption {
	return func(c *Config) {
		c.Tags = tags
	}
}

// WithConfigMetadata returns an option that can append Metadatas to Config.Metadata
func WithConfigMetadata(key string, value interface{}) ConfigOption {
	return func(c *Config) {
		c.Metadata[key] = value
	}
}

// SetConfigMetadata returns an option that can set Metadata on a Config
func SetConfigMetadata(metadata map[string]interface{}) ConfigOption {
	return func(c *Config) {
		c.Metadata = metadata
	}
}

// WithConfigDebug returns an option that can set Debug on a Config
func WithConfigDebug(debug bool) ConfigOption {
	return func(c *Config) {
		c.Debug = debug
	}
}

type ServerOption func(s *Server)

// NewServerWithOptions creates a new Server with the passed in options set
func NewServerWithOptions(opts ...ServerOption) *Server {
	s := &Server{}
	for _, o := range opts {
		o(s)
	}
	return s
}

// NewServerWithOptionsAndDefaults creates a new Server with the passed in options set starting from the defaults
func NewServerWithOptionsAndDefaults(opts ...ServerOption) *Server {
	s := &Server{}
	defaults.MustSet(s)
	for _, o := range opts {
		o(s)
	}
	return s
}

// ToOption returns a new ServerOption that sets the values from the passed in Server
func (s *Server) ToOption() ServerOption {
	return func(to *Server) {
		to.Host = s.Host
		to.Port = s.Port
		to.TLS = s.TLS
		to.Cert = s.Cert
		to.Key = s.Key
		to.Workers = s.Workers
	}
}

// DebugMap returns a map form of Server for debugging
func (s *Server) DebugMap() map[string]any {
	debugMap := map[string]any{}
	if s.Host == "" {
		debugMap["Host"] = "(empty)"
	} else {
		debugMap["Host"] = s.Host
	}
	debugMap["Port"] = s.Port
	debugMap["TLS"] = s.TLS
	if s.Cert == "" {
		debugMap["Cert"] = "(empty)"
	} else {
		debugMap["Cert"] = "(sensitive)"
	}
	if s.Key == "" {
		debugMap["Key"] = "(empty)"
	} else {
		debugMap["Key"] = "(sensitive)"
	}
	debugMap["Workers"] = s.Workers
	return debugMap
}

// ServerWithOptions configures an existing Server with the passed in options set
func ServerWithOptions(s *Server, opts ...ServerOption) *Server {
	for _, o := range opts {
		o(s)
	}
	return s
}

// WithOptions configures the receiver Server with the passed in options set
func (s *Server) WithOptions(opts ...ServerOption) *Server {
	for _, o := range opts {
		o(s)
	}
	return s
}

// WithServerHost returns an option that can set Host on a Server
func WithServerHost(host string) ServerOption {
	return func(s *Server) {
		s.Host = host
	}
}

// WithServerPort returns an option that can set Port on a Server
func WithServerPort(port int) ServerOption {
	return func(s *Server) {
		s.Port = port
	}
}

// WithServerTLS returns an option that can set TLS on a Server
func WithServerTLS(tLS bool) ServerOption {
	return func(s *Server) {
		s.TLS = tLS
	}
}

// WithServerCert returns an option that can set Cert on a Server
func WithServerCert(cert string) ServerOption {
	return func(s *Server) {
		s.Cert = cert
	}
}

// WithServerKey returns an option that can set Key on a Server
func WithServerKey(key string) ServerOption {
	return func(s *Server) {
		s.Key = key
	}
}

// WithServerWorkers returns an option that can set Workers on a Server
func WithServerWorkers(workers int) ServerOption {
	return func(s *Server) {
		s.Workers = workers
	}
}
