// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package testdata

import (
	"database/sql"
	defaults "github.com/creasty/defaults"
)

type DatabaseConfigOption func(d *DatabaseConfig)

// NewDatabaseConfigWithOptions creates a new DatabaseConfig with the passed in options set
func NewDatabaseConfigWithOptions(opts ...DatabaseConfigOption) *DatabaseConfig {
	d := &DatabaseConfig{}
	for _, o := range opts {
		o(d)
	}
	return d
}

// NewDatabaseConfigWithOptionsAndDefaults creates a new DatabaseConfig with the passed in options set starting from the defaults
func NewDatabaseConfigWithOptionsAndDefaults(opts ...DatabaseConfigOption) *DatabaseConfig {
	d := &DatabaseConfig{}
	defaults.MustSet(d)
	for _, o := range opts {
		o(d)
	}
	return d
}

// ToOption returns a new DatabaseConfigOption that sets the values from the passed in DatabaseConfig
func (d *DatabaseConfig) ToOption() DatabaseConfigOption {
	return func(to *DatabaseConfig) {
		to.ConnectionString = d.ConnectionString
		to.MaxConnections = d.MaxConnections
		to.Enabled = d.Enabled
	}
}

// DebugMap returns a map form of DatabaseConfig for debugging
func (d *DatabaseConfig) DebugMap() map[string]any {
	debugMap := map[string]any{}
	debugMap["ConnectionString"] = "(sensitive)"
	debugMap["MaxConnections"] = d.MaxConnections
	debugMap["Enabled"] = d.Enabled
	return debugMap
}

// FlatDebugMap returns a flattened map form of DatabaseConfig for debugging
// Nested maps are flattened using dot notation (e.g., "parent.child.field")
func (d *DatabaseConfig) FlatDebugMap() map[string]any {
	return flattenDebugMap(d.DebugMap())
}

// DatabaseConfigWithOptions configures an existing DatabaseConfig with the passed in options set
func DatabaseConfigWithOptions(d *DatabaseConfig, opts ...DatabaseConfigOption) *DatabaseConfig {
	for _, o := range opts {
		o(d)
	}
	return d
}

// WithOptions configures the receiver DatabaseConfig with the passed in options set
func (d *DatabaseConfig) WithOptions(opts ...DatabaseConfigOption) *DatabaseConfig {
	for _, o := range opts {
		o(d)
	}
	return d
}

// WithConnectionString returns an option that can set ConnectionString on a DatabaseConfig
func WithConnectionString(connectionString sql.NullString) DatabaseConfigOption {
	return func(d *DatabaseConfig) {
		d.ConnectionString = connectionString
	}
}

// WithMaxConnections returns an option that can set MaxConnections on a DatabaseConfig
func WithMaxConnections(maxConnections sql.NullInt64) DatabaseConfigOption {
	return func(d *DatabaseConfig) {
		d.MaxConnections = maxConnections
	}
}

// WithEnabled returns an option that can set Enabled on a DatabaseConfig
func WithEnabled(enabled bool) DatabaseConfigOption {
	return func(d *DatabaseConfig) {
		d.Enabled = enabled
	}
}

// flattenDebugMap recursively flattens nested maps using dot notation
func flattenDebugMap(debugMap map[string]any) map[string]any {
	flattened := make(map[string]any, len(debugMap))
	for key, value := range debugMap {
		childMap, ok := value.(map[string]any)
		if ok {
			for fk, fv := range flattenDebugMap(childMap) {
				flattened[key+"."+fk] = fv
			}
			continue
		}
		flattened[key] = value
	}
	return flattened
}
