// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package testdata

import (
	"fmt"
	defaults "github.com/creasty/defaults"
)

type GenericConfigOption func(g *GenericConfig)

// NewGenericConfigWithOptions creates a new GenericConfig with the passed in options set
func NewGenericConfigWithOptions(opts ...GenericConfigOption) *GenericConfig {
	g := &GenericConfig{}
	for _, o := range opts {
		o(g)
	}
	return g
}

// NewGenericConfigWithOptionsAndDefaults creates a new GenericConfig with the passed in options set starting from the defaults
func NewGenericConfigWithOptionsAndDefaults(opts ...GenericConfigOption) *GenericConfig {
	g := &GenericConfig{}
	defaults.MustSet(g)
	for _, o := range opts {
		o(g)
	}
	return g
}

// ToOption returns a new GenericConfigOption that sets the values from the passed in GenericConfig
func (g *GenericConfig) ToOption() GenericConfigOption {
	return func(to *GenericConfig) {
		to.StringContainer = g.StringContainer
		to.IntContainer = g.IntContainer
		to.StringIntPair = g.StringIntPair
		to.Containers = g.Containers
		to.Pairs = g.Pairs
		to.OptionalContainer = g.OptionalContainer
		to.ContainerMap = g.ContainerMap
	}
}

// DebugMap returns a map form of GenericConfig for debugging
func (g *GenericConfig) DebugMap() map[string]any {
	debugMap := map[string]any{}
	debugMap["StringContainer"] = g.StringContainer
	debugMap["IntContainer"] = g.IntContainer
	debugMap["StringIntPair"] = g.StringIntPair
	if g.Containers == nil {
		debugMap["Containers"] = "nil"
	} else {
		debugMap["Containers"] = fmt.Sprintf("(slice of size %d)", len(g.Containers))
	}
	if g.Pairs == nil {
		debugMap["Pairs"] = "nil"
	} else {
		debugMap["Pairs"] = fmt.Sprintf("(slice of size %d)", len(g.Pairs))
	}
	if g.OptionalContainer == nil {
		debugMap["OptionalContainer"] = "nil"
	} else {
		debugMap["OptionalContainer"] = *g.OptionalContainer
	}
	if g.ContainerMap == nil {
		debugMap["ContainerMap"] = "nil"
	} else {
		debugMap["ContainerMap"] = fmt.Sprintf("(map of size %d)", len(g.ContainerMap))
	}
	return debugMap
}

// FlatDebugMap returns a flattened map form of GenericConfig for debugging
// Nested maps are flattened using dot notation (e.g., "parent.child.field")
func (g *GenericConfig) FlatDebugMap() map[string]any {
	var flatten func(m map[string]any) map[string]any
	flatten = func(m map[string]any) map[string]any {
		result := make(map[string]any, len(m))
		for key, value := range m {
			childMap, ok := value.(map[string]any)
			if ok {
				for childKey, childValue := range flatten(childMap) {
					result[key+"."+childKey] = childValue
				}
				continue
			}
			result[key] = value
		}
		return result
	}
	return flatten(g.DebugMap())
}

// GenericConfigWithOptions configures an existing GenericConfig with the passed in options set
func GenericConfigWithOptions(g *GenericConfig, opts ...GenericConfigOption) *GenericConfig {
	for _, o := range opts {
		o(g)
	}
	return g
}

// WithOptions configures the receiver GenericConfig with the passed in options set
func (g *GenericConfig) WithOptions(opts ...GenericConfigOption) *GenericConfig {
	for _, o := range opts {
		o(g)
	}
	return g
}

// WithStringContainer returns an option that can set StringContainer on a GenericConfig
func WithStringContainer(stringContainer Container[string]) GenericConfigOption {
	return func(g *GenericConfig) {
		g.StringContainer = stringContainer
	}
}

// WithIntContainer returns an option that can set IntContainer on a GenericConfig
func WithIntContainer(intContainer Container[int]) GenericConfigOption {
	return func(g *GenericConfig) {
		g.IntContainer = intContainer
	}
}

// WithStringIntPair returns an option that can set StringIntPair on a GenericConfig
func WithStringIntPair(stringIntPair Pair[string, int]) GenericConfigOption {
	return func(g *GenericConfig) {
		g.StringIntPair = stringIntPair
	}
}

// WithContainers returns an option that can append Containerss to GenericConfig.Containers
func WithContainers(containers Container[string]) GenericConfigOption {
	return func(g *GenericConfig) {
		g.Containers = append(g.Containers, containers)
	}
}

// SetContainers returns an option that can set Containers on a GenericConfig
func SetContainers(containers []Container[string]) GenericConfigOption {
	return func(g *GenericConfig) {
		g.Containers = containers
	}
}

// WithPairs returns an option that can append Pairss to GenericConfig.Pairs
func WithPairs(pairs Pair[int, string]) GenericConfigOption {
	return func(g *GenericConfig) {
		g.Pairs = append(g.Pairs, pairs)
	}
}

// SetPairs returns an option that can set Pairs on a GenericConfig
func SetPairs(pairs []Pair[int, string]) GenericConfigOption {
	return func(g *GenericConfig) {
		g.Pairs = pairs
	}
}

// WithOptionalContainer returns an option that can set OptionalContainer on a GenericConfig
func WithOptionalContainer(optionalContainer *Container[bool]) GenericConfigOption {
	return func(g *GenericConfig) {
		g.OptionalContainer = optionalContainer
	}
}

// WithContainerMap returns an option that can append ContainerMaps to GenericConfig.ContainerMap
func WithContainerMap(key string, value Container[int]) GenericConfigOption {
	return func(g *GenericConfig) {
		g.ContainerMap[key] = value
	}
}

// SetContainerMap returns an option that can set ContainerMap on a GenericConfig
func SetContainerMap(containerMap map[string]Container[int]) GenericConfigOption {
	return func(g *GenericConfig) {
		g.ContainerMap = containerMap
	}
}
