// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package testdata

import defaults "github.com/creasty/defaults"

type HiddenFieldsOption func(h *HiddenFields)

// NewHiddenFieldsWithOptions creates a new HiddenFields with the passed in options set
func NewHiddenFieldsWithOptions(opts ...HiddenFieldsOption) *HiddenFields {
	h := &HiddenFields{}
	for _, o := range opts {
		o(h)
	}
	return h
}

// NewHiddenFieldsWithOptionsAndDefaults creates a new HiddenFields with the passed in options set starting from the defaults
func NewHiddenFieldsWithOptionsAndDefaults(opts ...HiddenFieldsOption) *HiddenFields {
	h := &HiddenFields{}
	defaults.MustSet(h)
	for _, o := range opts {
		o(h)
	}
	return h
}

// ToOption returns a new HiddenFieldsOption that sets the values from the passed in HiddenFields
func (h *HiddenFields) ToOption() HiddenFieldsOption {
	return func(to *HiddenFields) {
		to.PublicName = h.PublicName
		to.HiddenField = h.HiddenField
		to.AnotherName = h.AnotherName
	}
}

// DebugMap returns a map form of HiddenFields for debugging
func (h *HiddenFields) DebugMap() map[string]any {
	debugMap := map[string]any{}
	if h.PublicName == "" {
		debugMap["PublicName"] = "(empty)"
	} else {
		debugMap["PublicName"] = h.PublicName
	}
	if h.AnotherName == "" {
		debugMap["AnotherName"] = "(empty)"
	} else {
		debugMap["AnotherName"] = h.AnotherName
	}
	return debugMap
}

// HiddenFieldsWithOptions configures an existing HiddenFields with the passed in options set
func HiddenFieldsWithOptions(h *HiddenFields, opts ...HiddenFieldsOption) *HiddenFields {
	for _, o := range opts {
		o(h)
	}
	return h
}

// WithOptions configures the receiver HiddenFields with the passed in options set
func (h *HiddenFields) WithOptions(opts ...HiddenFieldsOption) *HiddenFields {
	for _, o := range opts {
		o(h)
	}
	return h
}

// WithPublicName returns an option that can set PublicName on a HiddenFields
func WithPublicName(publicName string) HiddenFieldsOption {
	return func(h *HiddenFields) {
		h.PublicName = publicName
	}
}

// WithHiddenField returns an option that can set HiddenField on a HiddenFields
func WithHiddenField(hiddenField string) HiddenFieldsOption {
	return func(h *HiddenFields) {
		h.HiddenField = hiddenField
	}
}

// WithAnotherName returns an option that can set AnotherName on a HiddenFields
func WithAnotherName(anotherName string) HiddenFieldsOption {
	return func(h *HiddenFields) {
		h.AnotherName = anotherName
	}
}
