// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package testdata

import defaults "github.com/creasty/defaults"

type UnexportedTestOption func(u *UnexportedTest)

// NewUnexportedTestWithOptions creates a new UnexportedTest with the passed in options set
func NewUnexportedTestWithOptions(opts ...UnexportedTestOption) *UnexportedTest {
	u := &UnexportedTest{}
	for _, o := range opts {
		o(u)
	}
	return u
}

// NewUnexportedTestWithOptionsAndDefaults creates a new UnexportedTest with the passed in options set starting from the defaults
func NewUnexportedTestWithOptionsAndDefaults(opts ...UnexportedTestOption) *UnexportedTest {
	u := &UnexportedTest{}
	defaults.MustSet(u)
	for _, o := range opts {
		o(u)
	}
	return u
}

// ToOption returns a new UnexportedTestOption that sets the values from the passed in UnexportedTest
func (u *UnexportedTest) ToOption() UnexportedTestOption {
	return func(to *UnexportedTest) {
		to.Host = u.Host
		to.Cache = u.Cache
	}
}

// DebugMap returns a map form of UnexportedTest for debugging
func (u *UnexportedTest) DebugMap() map[string]any {
	debugMap := map[string]any{}
	if u.Host == "" {
		debugMap["Host"] = "(empty)"
	} else {
		debugMap["Host"] = u.Host
	}
	return debugMap
}

// FlatDebugMap returns a flattened map form of UnexportedTest for debugging
// Nested maps are flattened using dot notation (e.g., "parent.child.field")
func (u *UnexportedTest) FlatDebugMap() map[string]any {
	var flatten func(m map[string]any) map[string]any
	flatten = func(m map[string]any) map[string]any {
		result := make(map[string]any, len(m))
		for key, value := range m {
			childMap, ok := value.(map[string]any)
			if ok {
				for childKey, childValue := range flatten(childMap) {
					result[key+"."+childKey] = childValue
				}
				continue
			}
			result[key] = value
		}
		return result
	}
	return flatten(u.DebugMap())
}

// UnexportedTestWithOptions configures an existing UnexportedTest with the passed in options set
func UnexportedTestWithOptions(u *UnexportedTest, opts ...UnexportedTestOption) *UnexportedTest {
	for _, o := range opts {
		o(u)
	}
	return u
}

// WithOptions configures the receiver UnexportedTest with the passed in options set
func (u *UnexportedTest) WithOptions(opts ...UnexportedTestOption) *UnexportedTest {
	for _, o := range opts {
		o(u)
	}
	return u
}

// WithHost returns an option that can set Host on a UnexportedTest
func WithHost(host string) UnexportedTestOption {
	return func(u *UnexportedTest) {
		u.Host = host
	}
}

// WithMaxRetries returns an option that can set MaxRetries on a UnexportedTest
func WithMaxRetries(maxRetries int) UnexportedTestOption {
	return func(u *UnexportedTest) {
		u.MaxRetries = maxRetries
	}
}

// withBuffer returns an option that can append Buffers to UnexportedTest.Buffer
func withBuffer(buffer byte) UnexportedTestOption {
	return func(u *UnexportedTest) {
		u.Buffer = append(u.Buffer, buffer)
	}
}

// setBuffer returns an option that can set Buffer on a UnexportedTest
func setBuffer(buffer []byte) UnexportedTestOption {
	return func(u *UnexportedTest) {
		u.Buffer = buffer
	}
}

// withCache returns an option that can append Caches to UnexportedTest.Cache
func withCache(key string, value any) UnexportedTestOption {
	return func(u *UnexportedTest) {
		u.Cache[key] = value
	}
}

// setCache returns an option that can set Cache on a UnexportedTest
func setCache(cache map[string]any) UnexportedTestOption {
	return func(u *UnexportedTest) {
		u.Cache = cache
	}
}
