// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package testdata

import defaults "github.com/creasty/defaults"

type CredentialsOption func(c *Credentials)

// NewCredentialsWithOptions creates a new Credentials with the passed in options set
func NewCredentialsWithOptions(opts ...CredentialsOption) *Credentials {
	c := &Credentials{}
	for _, o := range opts {
		o(c)
	}
	return c
}

// NewCredentialsWithOptionsAndDefaults creates a new Credentials with the passed in options set starting from the defaults
func NewCredentialsWithOptionsAndDefaults(opts ...CredentialsOption) *Credentials {
	c := &Credentials{}
	defaults.MustSet(c)
	for _, o := range opts {
		o(c)
	}
	return c
}

// ToOption returns a new CredentialsOption that sets the values from the passed in Credentials
func (c *Credentials) ToOption() CredentialsOption {
	return func(to *Credentials) {
		to.Username = c.Username
		to.Password = c.Password
		to.APIKey = c.APIKey
		to.Host = c.Host
	}
}

// DebugMap returns a map form of Credentials for debugging
func (c *Credentials) DebugMap() map[string]any {
	debugMap := map[string]any{}
	if c.Username == "" {
		debugMap["Username"] = "(empty)"
	} else {
		debugMap["Username"] = c.Username
	}
	if c.Password == "" {
		debugMap["Password"] = "(empty)"
	} else {
		debugMap["Password"] = "(sensitive)"
	}
	if c.APIKey == "" {
		debugMap["APIKey"] = "(empty)"
	} else {
		debugMap["APIKey"] = "(sensitive)"
	}
	if c.Host == "" {
		debugMap["Host"] = "(empty)"
	} else {
		debugMap["Host"] = c.Host
	}
	return debugMap
}

// CredentialsWithOptions configures an existing Credentials with the passed in options set
func CredentialsWithOptions(c *Credentials, opts ...CredentialsOption) *Credentials {
	for _, o := range opts {
		o(c)
	}
	return c
}

// WithOptions configures the receiver Credentials with the passed in options set
func (c *Credentials) WithOptions(opts ...CredentialsOption) *Credentials {
	for _, o := range opts {
		o(c)
	}
	return c
}

// WithUsername returns an option that can set Username on a Credentials
func WithUsername(username string) CredentialsOption {
	return func(c *Credentials) {
		c.Username = username
	}
}

// WithPassword returns an option that can set Password on a Credentials
func WithPassword(password string) CredentialsOption {
	return func(c *Credentials) {
		c.Password = password
	}
}

// WithAPIKey returns an option that can set APIKey on a Credentials
func WithAPIKey(aPIKey string) CredentialsOption {
	return func(c *Credentials) {
		c.APIKey = aPIKey
	}
}

// WithHost returns an option that can set Host on a Credentials
func WithHost(host string) CredentialsOption {
	return func(c *Credentials) {
		c.Host = host
	}
}
