// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package testdata

import defaults "github.com/creasty/defaults"

type ServerMetadataOption func(s *ServerMetadata)

// NewServerMetadataWithOptions creates a new ServerMetadata with the passed in options set
func NewServerMetadataWithOptions(opts ...ServerMetadataOption) *ServerMetadata {
	s := &ServerMetadata{}
	for _, o := range opts {
		o(s)
	}
	return s
}

// NewServerMetadataWithOptionsAndDefaults creates a new ServerMetadata with the passed in options set starting from the defaults
func NewServerMetadataWithOptionsAndDefaults(opts ...ServerMetadataOption) *ServerMetadata {
	s := &ServerMetadata{}
	defaults.MustSet(s)
	for _, o := range opts {
		o(s)
	}
	return s
}

// ToOption returns a new ServerMetadataOption that sets the values from the passed in ServerMetadata
func (s *ServerMetadata) ToOption() ServerMetadataOption {
	return func(to *ServerMetadata) {
		to.Name = s.Name
		to.Owner = s.Owner
	}
}

// DebugMap returns a map form of ServerMetadata for debugging
func (s *ServerMetadata) DebugMap() map[string]any {
	debugMap := map[string]any{}
	if s.Name == "" {
		debugMap["Name"] = "(empty)"
	} else {
		debugMap["Name"] = s.Name
	}
	if s.Owner == "" {
		debugMap["Owner"] = "(empty)"
	} else {
		debugMap["Owner"] = s.Owner
	}
	return debugMap
}

// FlatDebugMap returns a flattened map form of ServerMetadata for debugging
// Nested maps are flattened using dot notation (e.g., "parent.child.field")
func (s *ServerMetadata) FlatDebugMap() map[string]any {
	var flatten func(m map[string]any) map[string]any
	flatten = func(m map[string]any) map[string]any {
		result := make(map[string]any, len(m))
		for key, value := range m {
			childMap, ok := value.(map[string]any)
			if ok {
				for childKey, childValue := range flatten(childMap) {
					result[key+"."+childKey] = childValue
				}
				continue
			}
			result[key] = value
		}
		return result
	}
	return flatten(s.DebugMap())
}

// ServerMetadataWithOptions configures an existing ServerMetadata with the passed in options set
func ServerMetadataWithOptions(s *ServerMetadata, opts ...ServerMetadataOption) *ServerMetadata {
	for _, o := range opts {
		o(s)
	}
	return s
}

// WithOptions configures the receiver ServerMetadata with the passed in options set
func (s *ServerMetadata) WithOptions(opts ...ServerMetadataOption) *ServerMetadata {
	for _, o := range opts {
		o(s)
	}
	return s
}

// WithName returns an option that can set Name on a ServerMetadata
func WithName(name string) ServerMetadataOption {
	return func(s *ServerMetadata) {
		s.Name = name
	}
}

// WithOwner returns an option that can set Owner on a ServerMetadata
func WithOwner(owner string) ServerMetadataOption {
	return func(s *ServerMetadata) {
		s.Owner = owner
	}
}

type ConfigOption func(c *Config)

// NewConfigWithOptions creates a new Config with the passed in options set
func NewConfigWithOptions(opts ...ConfigOption) *Config {
	c := &Config{}
	for _, o := range opts {
		o(c)
	}
	return c
}

// NewConfigWithOptionsAndDefaults creates a new Config with the passed in options set starting from the defaults
func NewConfigWithOptionsAndDefaults(opts ...ConfigOption) *Config {
	c := &Config{}
	defaults.MustSet(c)
	for _, o := range opts {
		o(c)
	}
	return c
}

// ToOption returns a new ConfigOption that sets the values from the passed in Config
func (c *Config) ToOption() ConfigOption {
	return func(to *Config) {
		to.Port = c.Port
		to.Metadata = c.Metadata
	}
}

// DebugMap returns a map form of Config for debugging
func (c *Config) DebugMap() map[string]any {
	debugMap := map[string]any{}
	debugMap["Port"] = c.Port
	debugMap["Metadata"] = c.Metadata.DebugMap()
	return debugMap
}

// FlatDebugMap returns a flattened map form of Config for debugging
// Nested maps are flattened using dot notation (e.g., "parent.child.field")
func (c *Config) FlatDebugMap() map[string]any {
	var flatten func(m map[string]any) map[string]any
	flatten = func(m map[string]any) map[string]any {
		result := make(map[string]any, len(m))
		for key, value := range m {
			childMap, ok := value.(map[string]any)
			if ok {
				for childKey, childValue := range flatten(childMap) {
					result[key+"."+childKey] = childValue
				}
				continue
			}
			result[key] = value
		}
		return result
	}
	return flatten(c.DebugMap())
}

// ConfigWithOptions configures an existing Config with the passed in options set
func ConfigWithOptions(c *Config, opts ...ConfigOption) *Config {
	for _, o := range opts {
		o(c)
	}
	return c
}

// WithOptions configures the receiver Config with the passed in options set
func (c *Config) WithOptions(opts ...ConfigOption) *Config {
	for _, o := range opts {
		o(c)
	}
	return c
}

// WithPort returns an option that can set Port on a Config
func WithPort(port int) ConfigOption {
	return func(c *Config) {
		c.Port = port
	}
}

// WithMetadata returns an option that can set Metadata on a Config
func WithMetadata(metadata ServerMetadata) ConfigOption {
	return func(c *Config) {
		c.Metadata = metadata
	}
}

// WithMetadataOptions returns an option that can set Metadata on a Config using nested options
func WithMetadataOptions(opts ...ServerMetadataOption) ConfigOption {
	return func(c *Config) {
		c.Metadata = *NewServerMetadataWithOptions(opts...)
	}
}
