// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package testdata

import defaults "github.com/creasty/defaults"

type OuterConfigOption func(o *OuterConfig)

// NewOuterConfigWithOptions creates a new OuterConfig with the passed in options set
func NewOuterConfigWithOptions(opts ...OuterConfigOption) *OuterConfig {
	o := &OuterConfig{}
	for _, o := range opts {
		o(o)
	}
	return o
}

// NewOuterConfigWithOptionsAndDefaults creates a new OuterConfig with the passed in options set starting from the defaults
func NewOuterConfigWithOptionsAndDefaults(opts ...OuterConfigOption) *OuterConfig {
	o := &OuterConfig{}
	defaults.MustSet(o)
	for _, o := range opts {
		o(o)
	}
	return o
}

// ToOption returns a new OuterConfigOption that sets the values from the passed in OuterConfig
func (o *OuterConfig) ToOption() OuterConfigOption {
	return func(to *OuterConfig) {
		to.Name = o.Name
		to.Nested = o.Nested
		to.NestedPtr = o.NestedPtr
	}
}

// DebugMap returns a map form of OuterConfig for debugging
func (o *OuterConfig) DebugMap() map[string]any {
	debugMap := map[string]any{}
	if o.Name == "" {
		debugMap["Name"] = "(empty)"
	} else {
		debugMap["Name"] = o.Name
	}
	if dm, ok := any(o.Nested).(interface {
		DebugMap() map[string]any
	}); ok {
		debugMap["Nested"] = dm.DebugMap()
	} else {
		debugMap["Nested"] = o.Nested
	}
	if o.NestedPtr == nil {
		debugMap["NestedPtr"] = "nil"
	} else if dm, ok := any(o.NestedPtr).(interface {
		DebugMap() map[string]any
	}); ok {
		debugMap["NestedPtr"] = dm.DebugMap()
	} else {
		debugMap["NestedPtr"] = *o.NestedPtr
	}
	return debugMap
}

// FlatDebugMap returns a flattened map form of OuterConfig for debugging
// Nested maps are flattened using dot notation (e.g., "parent.child.field")
func (o *OuterConfig) FlatDebugMap() map[string]any {
	var flatten func(m map[string]any) map[string]any
	flatten = func(m map[string]any) map[string]any {
		result := make(map[string]any, len(m))
		for key, value := range m {
			childMap, ok := value.(map[string]any)
			if ok {
				for childKey, childValue := range flatten(childMap) {
					result[key+"."+childKey] = childValue
				}
				continue
			}
			result[key] = value
		}
		return result
	}
	return flatten(o.DebugMap())
}

// OuterConfigWithOptions configures an existing OuterConfig with the passed in options set
func OuterConfigWithOptions(o *OuterConfig, opts ...OuterConfigOption) *OuterConfig {
	for _, o := range opts {
		o(o)
	}
	return o
}

// WithOptions configures the receiver OuterConfig with the passed in options set
func (o *OuterConfig) WithOptions(opts ...OuterConfigOption) *OuterConfig {
	for _, o := range opts {
		o(o)
	}
	return o
}

// WithName returns an option that can set Name on a OuterConfig
func WithName(name string) OuterConfigOption {
	return func(o *OuterConfig) {
		o.Name = name
	}
}

// WithNested returns an option that can set Nested on a OuterConfig
func WithNested(nested NestedConfig) OuterConfigOption {
	return func(o *OuterConfig) {
		o.Nested = nested
	}
}

// WithNestedPtr returns an option that can set NestedPtr on a OuterConfig
func WithNestedPtr(nestedPtr *NestedConfig) OuterConfigOption {
	return func(o *OuterConfig) {
		o.NestedPtr = nestedPtr
	}
}
