// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package testdata

import (
	"fmt"
	defaults "github.com/creasty/defaults"
)

type ComplexConfigOption func(c *ComplexConfig)

// NewComplexConfigWithOptions creates a new ComplexConfig with the passed in options set
func NewComplexConfigWithOptions(opts ...ComplexConfigOption) *ComplexConfig {
	c := &ComplexConfig{}
	for _, o := range opts {
		o(c)
	}
	return c
}

// NewComplexConfigWithOptionsAndDefaults creates a new ComplexConfig with the passed in options set starting from the defaults
func NewComplexConfigWithOptionsAndDefaults(opts ...ComplexConfigOption) *ComplexConfig {
	c := &ComplexConfig{}
	defaults.MustSet(c)
	for _, o := range opts {
		o(c)
	}
	return c
}

// ToOption returns a new ComplexConfigOption that sets the values from the passed in ComplexConfig
func (c *ComplexConfig) ToOption() ComplexConfigOption {
	return func(to *ComplexConfig) {
		to.Database = c.Database
		to.Logger = c.Logger
		to.OnError = c.OnError
		to.Backup = c.Backup
	}
}

// DebugMap returns a map form of ComplexConfig for debugging
func (c *ComplexConfig) DebugMap() map[string]any {
	debugMap := map[string]any{}
	if dm, ok := interface{}(c.Database).(interface {
		DebugMap() map[string]any
	}); ok {
		debugMap["Database"] = dm.DebugMap()
	} else {
		debugMap["Database"] = fmt.Sprintf("%+v", c.Database)
	}
	if dm, ok := interface{}(c.Logger).(interface {
		DebugMap() map[string]any
	}); ok {
		debugMap["Logger"] = dm.DebugMap()
	} else {
		debugMap["Logger"] = fmt.Sprintf("%+v", c.Logger)
	}
	if c.OnError == nil {
		debugMap["OnError"] = "nil"
	} else {
		debugMap["OnError"] = fmt.Sprintf("%T", c.OnError)
	}
	if dm, ok := interface{}(c.Backup).(interface {
		DebugMap() map[string]any
	}); ok {
		debugMap["Backup"] = dm.DebugMap()
	} else {
		debugMap["Backup"] = fmt.Sprintf("%+v", c.Backup)
	}
	return debugMap
}

// FlatDebugMap returns a flattened map form of ComplexConfig for debugging
// Nested maps are flattened using dot notation (e.g., "parent.child.field")
func (c *ComplexConfig) FlatDebugMap() map[string]any {
	var flatten func(m map[string]any) map[string]any
	flatten = func(m map[string]any) map[string]any {
		result := make(map[string]any, len(m))
		for key, value := range m {
			childMap, ok := value.(map[string]any)
			if ok {
				for childKey, childValue := range flatten(childMap) {
					result[key+"."+childKey] = childValue
				}
				continue
			}
			result[key] = value
		}
		return result
	}
	return flatten(c.DebugMap())
}

// ComplexConfigWithOptions configures an existing ComplexConfig with the passed in options set
func ComplexConfigWithOptions(c *ComplexConfig, opts ...ComplexConfigOption) *ComplexConfig {
	for _, o := range opts {
		o(c)
	}
	return c
}

// WithOptions configures the receiver ComplexConfig with the passed in options set
func (c *ComplexConfig) WithOptions(opts ...ComplexConfigOption) *ComplexConfig {
	for _, o := range opts {
		o(c)
	}
	return c
}

// WithDatabase returns an option that can set Database on a ComplexConfig
func WithDatabase(database Nested) ComplexConfigOption {
	return func(c *ComplexConfig) {
		c.Database = database
	}
}

// WithLogger returns an option that can set Logger on a ComplexConfig
func WithLogger(logger Stringer) ComplexConfigOption {
	return func(c *ComplexConfig) {
		c.Logger = logger
	}
}

// WithOnError returns an option that can set OnError on a ComplexConfig
func WithOnError(onError interface{}) ComplexConfigOption {
	return func(c *ComplexConfig) {
		c.OnError = onError
	}
}

// WithBackup returns an option that can set Backup on a ComplexConfig
func WithBackup(backup Nested) ComplexConfigOption {
	return func(c *ComplexConfig) {
		c.Backup = backup
	}
}
