// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package testdata

import (
	defaults "github.com/creasty/defaults"
	"time"
)

type CrossPackageOption func(c *CrossPackage)

// NewCrossPackageWithOptions creates a new CrossPackage with the passed in options set
func NewCrossPackageWithOptions(opts ...CrossPackageOption) *CrossPackage {
	c := &CrossPackage{}
	for _, o := range opts {
		o(c)
	}
	return c
}

// NewCrossPackageWithOptionsAndDefaults creates a new CrossPackage with the passed in options set starting from the defaults
func NewCrossPackageWithOptionsAndDefaults(opts ...CrossPackageOption) *CrossPackage {
	c := &CrossPackage{}
	defaults.MustSet(c)
	for _, o := range opts {
		o(c)
	}
	return c
}

// ToOption returns a new CrossPackageOption that sets the values from the passed in CrossPackage
func (c *CrossPackage) ToOption() CrossPackageOption {
	return func(to *CrossPackage) {
		to.Name = c.Name
		to.Timestamp = c.Timestamp
		to.Duration = c.Duration
	}
}

// DebugMap returns a map form of CrossPackage for debugging
func (c *CrossPackage) DebugMap() map[string]any {
	debugMap := map[string]any{}
	if c.Name == "" {
		debugMap["Name"] = "(empty)"
	} else {
		debugMap["Name"] = c.Name
	}
	debugMap["Timestamp"] = c.Timestamp
	debugMap["Duration"] = c.Duration
	return debugMap
}

// FlatDebugMap returns a flattened map form of CrossPackage for debugging
// Nested maps are flattened using dot notation (e.g., "parent.child.field")
func (c *CrossPackage) FlatDebugMap() map[string]any {
	return flattenDebugMap(c.DebugMap())
}

// CrossPackageWithOptions configures an existing CrossPackage with the passed in options set
func CrossPackageWithOptions(c *CrossPackage, opts ...CrossPackageOption) *CrossPackage {
	for _, o := range opts {
		o(c)
	}
	return c
}

// WithOptions configures the receiver CrossPackage with the passed in options set
func (c *CrossPackage) WithOptions(opts ...CrossPackageOption) *CrossPackage {
	for _, o := range opts {
		o(c)
	}
	return c
}

// WithName returns an option that can set Name on a CrossPackage
func WithName(name string) CrossPackageOption {
	return func(c *CrossPackage) {
		c.Name = name
	}
}

// WithTimestamp returns an option that can set Timestamp on a CrossPackage
func WithTimestamp(timestamp time.Time) CrossPackageOption {
	return func(c *CrossPackage) {
		c.Timestamp = timestamp
	}
}

// WithDuration returns an option that can set Duration on a CrossPackage
func WithDuration(duration time.Duration) CrossPackageOption {
	return func(c *CrossPackage) {
		c.Duration = duration
	}
}

// flattenDebugMap recursively flattens nested maps using dot notation
func flattenDebugMap(debugMap map[string]any) map[string]any {
	flattened := make(map[string]any, len(debugMap))
	for key, value := range debugMap {
		childMap, ok := value.(map[string]any)
		if ok {
			for fk, fv := range flattenDebugMap(childMap) {
				flattened[key+"."+fk] = fv
			}
			continue
		}
		flattened[key] = value
	}
	return flattened
}
