// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package testdata

import (
	"fmt"
	defaults "github.com/creasty/defaults"
)

type FormatTestOption func(f *FormatTest)

// NewFormatTestWithOptions creates a new FormatTest with the passed in options set
func NewFormatTestWithOptions(opts ...FormatTestOption) *FormatTest {
	f := &FormatTest{}
	for _, o := range opts {
		o(f)
	}
	return f
}

// NewFormatTestWithOptionsAndDefaults creates a new FormatTest with the passed in options set starting from the defaults
func NewFormatTestWithOptionsAndDefaults(opts ...FormatTestOption) *FormatTest {
	f := &FormatTest{}
	defaults.MustSet(f)
	for _, o := range opts {
		o(f)
	}
	return f
}

// ToOption returns a new FormatTestOption that sets the values from the passed in FormatTest
func (f *FormatTest) ToOption() FormatTestOption {
	return func(to *FormatTest) {
		to.Name = f.Name
		to.Data = f.Data
		to.Count = f.Count
	}
}

// DebugMap returns a map form of FormatTest for debugging
func (f *FormatTest) DebugMap() map[string]any {
	debugMap := map[string]any{}
	if f.Name == "" {
		debugMap["Name"] = "(empty)"
	} else {
		debugMap["Name"] = f.Name
	}
	if f.Data == nil {
		debugMap["Data"] = "nil"
	} else {
		debugMap["Data"] = fmt.Sprintf("%v", f.Data)
	}
	debugMap["Count"] = f.Count
	return debugMap
}

// FormatTestWithOptions configures an existing FormatTest with the passed in options set
func FormatTestWithOptions(f *FormatTest, opts ...FormatTestOption) *FormatTest {
	for _, o := range opts {
		o(f)
	}
	return f
}

// WithOptions configures the receiver FormatTest with the passed in options set
func (f *FormatTest) WithOptions(opts ...FormatTestOption) *FormatTest {
	for _, o := range opts {
		o(f)
	}
	return f
}

// WithName returns an option that can set Name on a FormatTest
func WithName(name string) FormatTestOption {
	return func(f *FormatTest) {
		f.Name = name
	}
}

// WithData returns an option that can append Datas to FormatTest.Data
func WithData(key string, value string) FormatTestOption {
	return func(f *FormatTest) {
		f.Data[key] = value
	}
}

// SetData returns an option that can set Data on a FormatTest
func SetData(data map[string]string) FormatTestOption {
	return func(f *FormatTest) {
		f.Data = data
	}
}

// WithCount returns an option that can set Count on a FormatTest
func WithCount(count int) FormatTestOption {
	return func(f *FormatTest) {
		f.Count = count
	}
}
