// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package testdata

import defaults "github.com/creasty/defaults"

type AddressOption func(a *Address)

// NewAddressWithOptions creates a new Address with the passed in options set
func NewAddressWithOptions(opts ...AddressOption) *Address {
	a := &Address{}
	for _, o := range opts {
		o(a)
	}
	return a
}

// NewAddressWithOptionsAndDefaults creates a new Address with the passed in options set starting from the defaults
func NewAddressWithOptionsAndDefaults(opts ...AddressOption) *Address {
	a := &Address{}
	defaults.MustSet(a)
	for _, o := range opts {
		o(a)
	}
	return a
}

// ToOption returns a new AddressOption that sets the values from the passed in Address
func (a *Address) ToOption() AddressOption {
	return func(to *Address) {
		to.Street = a.Street
		to.City = a.City
	}
}

// DebugMap returns a map form of Address for debugging
func (a *Address) DebugMap() map[string]any {
	debugMap := map[string]any{}
	if a.Street == "" {
		debugMap["Street"] = "(empty)"
	} else {
		debugMap["Street"] = a.Street
	}
	if a.City == "" {
		debugMap["City"] = "(empty)"
	} else {
		debugMap["City"] = a.City
	}
	return debugMap
}

// FlatDebugMap returns a flattened map form of Address for debugging
// Nested maps are flattened using dot notation (e.g., "parent.child.field")
func (a *Address) FlatDebugMap() map[string]any {
	var flatten func(m map[string]any) map[string]any
	flatten = func(m map[string]any) map[string]any {
		result := make(map[string]any, len(m))
		for key, value := range m {
			childMap, ok := value.(map[string]any)
			if ok {
				for childKey, childValue := range flatten(childMap) {
					result[key+"."+childKey] = childValue
				}
				continue
			}
			result[key] = value
		}
		return result
	}
	return flatten(a.DebugMap())
}

// AddressWithOptions configures an existing Address with the passed in options set
func AddressWithOptions(a *Address, opts ...AddressOption) *Address {
	for _, o := range opts {
		o(a)
	}
	return a
}

// WithOptions configures the receiver Address with the passed in options set
func (a *Address) WithOptions(opts ...AddressOption) *Address {
	for _, o := range opts {
		o(a)
	}
	return a
}

// WithStreet returns an option that can set Street on a Address
func WithStreet(street string) AddressOption {
	return func(a *Address) {
		a.Street = street
	}
}

// WithCity returns an option that can set City on a Address
func WithCity(city string) AddressOption {
	return func(a *Address) {
		a.City = city
	}
}

type ConfigOption func(c *Config)

// NewConfigWithOptions creates a new Config with the passed in options set
func NewConfigWithOptions(opts ...ConfigOption) *Config {
	c := &Config{}
	for _, o := range opts {
		o(c)
	}
	return c
}

// NewConfigWithOptionsAndDefaults creates a new Config with the passed in options set starting from the defaults
func NewConfigWithOptionsAndDefaults(opts ...ConfigOption) *Config {
	c := &Config{}
	defaults.MustSet(c)
	for _, o := range opts {
		o(c)
	}
	return c
}

// ToOption returns a new ConfigOption that sets the values from the passed in Config
func (c *Config) ToOption() ConfigOption {
	return func(to *Config) {
		to.Name = c.Name
		to.Address = c.Address
	}
}

// DebugMap returns a map form of Config for debugging
func (c *Config) DebugMap() map[string]any {
	debugMap := map[string]any{}
	if c.Name == "" {
		debugMap["Name"] = "(empty)"
	} else {
		debugMap["Name"] = c.Name
	}
	debugMap["Address"] = c.Address.DebugMap()
	return debugMap
}

// FlatDebugMap returns a flattened map form of Config for debugging
// Nested maps are flattened using dot notation (e.g., "parent.child.field")
func (c *Config) FlatDebugMap() map[string]any {
	var flatten func(m map[string]any) map[string]any
	flatten = func(m map[string]any) map[string]any {
		result := make(map[string]any, len(m))
		for key, value := range m {
			childMap, ok := value.(map[string]any)
			if ok {
				for childKey, childValue := range flatten(childMap) {
					result[key+"."+childKey] = childValue
				}
				continue
			}
			result[key] = value
		}
		return result
	}
	return flatten(c.DebugMap())
}

// ConfigWithOptions configures an existing Config with the passed in options set
func ConfigWithOptions(c *Config, opts ...ConfigOption) *Config {
	for _, o := range opts {
		o(c)
	}
	return c
}

// WithOptions configures the receiver Config with the passed in options set
func (c *Config) WithOptions(opts ...ConfigOption) *Config {
	for _, o := range opts {
		o(c)
	}
	return c
}

// WithName returns an option that can set Name on a Config
func WithName(name string) ConfigOption {
	return func(c *Config) {
		c.Name = name
	}
}

// WithAddress returns an option that can set Address on a Config
func WithAddress(address Address) ConfigOption {
	return func(c *Config) {
		c.Address = address
	}
}

// WithAddressStreet returns an option that can set Address.Street on a Config
func WithAddressStreet(street string) ConfigOption {
	return func(c *Config) {
		c.Address.Street = street
	}
}

// WithAddressCity returns an option that can set Address.City on a Config
func WithAddressCity(city string) ConfigOption {
	return func(c *Config) {
		c.Address.City = city
	}
}
